#!/usr/bin/python

import os
import subprocess
import argparse

parser = argparse.ArgumentParser(description='Switch terminal color scheme')
parser.add_argument(
    '-r',
    '--reverse',
    action='store_true',
    help='Reverse order'
)
args = parser.parse_args()

config_dir = os.path.join(
    os.getenv('HOME'), 
    '.config/termite'
)
config_file = os.path.join(config_dir, 'config')

theme_dir = os.path.join(config_dir, 'themes')
theme_links = [
    os.path.join(theme_dir, link)
    for link in sorted(os.listdir(theme_dir))
]

current_theme = os.readlink(config_file)
try:
    target_index = theme_links.index(current_theme)
except ValueError:
    target_index = 0
offset = -1 if args.reverse else 1
next_index = (target_index + offset) % len(theme_links)
next_theme = theme_links[next_index]
print(f"Using '{os.path.basename(next_theme)}'")

os.remove(config_file)
os.symlink(
    src=next_theme,
    dst=config_file
)
subprocess.call(['killall', '-USR1', 'termite'])
